namespace Finanzas.Vista
{
    partial class RazonesFinancieras
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose (bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent ()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RazonesFinancieras));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btn_pa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_cnt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_is = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanel1 = new Bunifu.Framework.UI.BunifuGradientPanel();
            this.bunifuCustomLabel1 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btn_salir = new Bunifu.Framework.UI.BunifuImageButton();
            this.bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.btn_RotInt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_deuda = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_PasivoCap = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.btn_ActivoTotal = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_ActivoFijo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_PeriCobro = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_rotaciónInventario = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_CuentasCobrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.btn_UtilidadNeta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_UtilidadBruta = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_UtilidadOper = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFlatButton1 = new Bunifu.Framework.UI.BunifuFlatButton();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.groupBox1.SuspendLayout();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btn_salir)).BeginInit();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.SuspendLayout();
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btn_pa);
            this.groupBox1.Controls.Add(this.btn_cnt);
            this.groupBox1.Controls.Add(this.btn_is);
            this.groupBox1.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox1.ForeColor = System.Drawing.Color.DodgerBlue;
            this.groupBox1.Location = new System.Drawing.Point(12, 79);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(438, 222);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Razones de liquidez";
            // 
            // btn_pa
            // 
            this.btn_pa.AllowToggling = false;
            this.btn_pa.AnimationSpeed = 200;
            this.btn_pa.AutoGenerateColors = false;
            this.btn_pa.BackColor = System.Drawing.Color.Transparent;
            this.btn_pa.BackColor1 = System.Drawing.Color.White;
            this.btn_pa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_pa.BackgroundImage")));
            this.btn_pa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_pa.ButtonText = "Prueba Ácida";
            this.btn_pa.ButtonTextMarginLeft = -57;
            this.btn_pa.ColorContrastOnClick = 45;
            this.btn_pa.ColorContrastOnHover = 45;
            this.btn_pa.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_pa.CustomizableEdges = borderEdges1;
            this.btn_pa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_pa.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_pa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_pa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_pa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_pa.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_pa.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_pa.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_pa.IconMarginLeft = 11;
            this.btn_pa.IconPadding = 10;
            this.btn_pa.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_pa.IdleBorderColor = System.Drawing.Color.White;
            this.btn_pa.IdleBorderRadius = 3;
            this.btn_pa.IdleBorderThickness = 1;
            this.btn_pa.IdleFillColor = System.Drawing.Color.White;
            this.btn_pa.IdleIconLeftImage = null;
            this.btn_pa.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_pa.IdleIconRightImage")));
            this.btn_pa.IndicateFocus = false;
            this.btn_pa.Location = new System.Drawing.Point(17, 145);
            this.btn_pa.Name = "btn_pa";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties1.BorderRadius = 3;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties1.IconRightImage")));
            this.btn_pa.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.White;
            stateProperties2.BorderRadius = 3;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties2.IconRightImage")));
            this.btn_pa.OnPressedState = stateProperties2;
            this.btn_pa.Size = new System.Drawing.Size(210, 45);
            this.btn_pa.TabIndex = 2;
            this.btn_pa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_pa.TextMarginLeft = -57;
            this.btn_pa.UseDefaultRadiusAndThickness = true;
            this.btn_pa.Click += new System.EventHandler(this.btn_pa_Click);
            // 
            // btn_cnt
            // 
            this.btn_cnt.AllowToggling = false;
            this.btn_cnt.AnimationSpeed = 200;
            this.btn_cnt.AutoGenerateColors = false;
            this.btn_cnt.BackColor = System.Drawing.Color.Transparent;
            this.btn_cnt.BackColor1 = System.Drawing.Color.White;
            this.btn_cnt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_cnt.BackgroundImage")));
            this.btn_cnt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_cnt.ButtonText = "Capital Neto Trabajo";
            this.btn_cnt.ButtonTextMarginLeft = -36;
            this.btn_cnt.ColorContrastOnClick = 45;
            this.btn_cnt.ColorContrastOnHover = 45;
            this.btn_cnt.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_cnt.CustomizableEdges = borderEdges2;
            this.btn_cnt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_cnt.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_cnt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_cnt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_cnt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_cnt.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_cnt.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_cnt.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_cnt.IconMarginLeft = 11;
            this.btn_cnt.IconPadding = 10;
            this.btn_cnt.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_cnt.IdleBorderColor = System.Drawing.Color.White;
            this.btn_cnt.IdleBorderRadius = 3;
            this.btn_cnt.IdleBorderThickness = 1;
            this.btn_cnt.IdleFillColor = System.Drawing.Color.White;
            this.btn_cnt.IdleIconLeftImage = null;
            this.btn_cnt.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_cnt.IdleIconRightImage")));
            this.btn_cnt.IndicateFocus = false;
            this.btn_cnt.Location = new System.Drawing.Point(17, 43);
            this.btn_cnt.Name = "btn_cnt";
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.BorderRadius = 3;
            stateProperties3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties3.BorderThickness = 1;
            stateProperties3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.ForeColor = System.Drawing.Color.White;
            stateProperties3.IconLeftImage = null;
            stateProperties3.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties3.IconRightImage")));
            this.btn_cnt.onHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.White;
            stateProperties4.BorderRadius = 3;
            stateProperties4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties4.BorderThickness = 1;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties4.IconLeftImage = null;
            stateProperties4.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties4.IconRightImage")));
            this.btn_cnt.OnPressedState = stateProperties4;
            this.btn_cnt.Size = new System.Drawing.Size(210, 45);
            this.btn_cnt.TabIndex = 1;
            this.btn_cnt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_cnt.TextMarginLeft = -36;
            this.btn_cnt.UseDefaultRadiusAndThickness = true;
            this.btn_cnt.Click += new System.EventHandler(this.btn_cnt_Click);
            // 
            // btn_is
            // 
            this.btn_is.AllowToggling = false;
            this.btn_is.AnimationSpeed = 200;
            this.btn_is.AutoGenerateColors = false;
            this.btn_is.BackColor = System.Drawing.Color.Transparent;
            this.btn_is.BackColor1 = System.Drawing.Color.White;
            this.btn_is.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_is.BackgroundImage")));
            this.btn_is.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_is.ButtonText = "Indice de solvencia";
            this.btn_is.ButtonTextMarginLeft = -40;
            this.btn_is.ColorContrastOnClick = 45;
            this.btn_is.ColorContrastOnHover = 45;
            this.btn_is.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_is.CustomizableEdges = borderEdges3;
            this.btn_is.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_is.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_is.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_is.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_is.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_is.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_is.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_is.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_is.IconMarginLeft = 11;
            this.btn_is.IconPadding = 10;
            this.btn_is.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_is.IdleBorderColor = System.Drawing.Color.White;
            this.btn_is.IdleBorderRadius = 3;
            this.btn_is.IdleBorderThickness = 1;
            this.btn_is.IdleFillColor = System.Drawing.Color.White;
            this.btn_is.IdleIconLeftImage = null;
            this.btn_is.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_is.IdleIconRightImage")));
            this.btn_is.IndicateFocus = false;
            this.btn_is.Location = new System.Drawing.Point(17, 94);
            this.btn_is.Name = "btn_is";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties5.BorderRadius = 3;
            stateProperties5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties5.BorderThickness = 1;
            stateProperties5.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties5.ForeColor = System.Drawing.Color.White;
            stateProperties5.IconLeftImage = null;
            stateProperties5.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties5.IconRightImage")));
            this.btn_is.onHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.White;
            stateProperties6.BorderRadius = 3;
            stateProperties6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties6.BorderThickness = 1;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties6.IconLeftImage = null;
            stateProperties6.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties6.IconRightImage")));
            this.btn_is.OnPressedState = stateProperties6;
            this.btn_is.Size = new System.Drawing.Size(210, 45);
            this.btn_is.TabIndex = 0;
            this.btn_is.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_is.TextMarginLeft = -40;
            this.btn_is.UseDefaultRadiusAndThickness = true;
            this.btn_is.Click += new System.EventHandler(this.btn_is_Click);
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuCustomLabel1);
            this.bunifuGradientPanel1.Controls.Add(this.btn_salir);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuDatePicker1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(980, 61);
            this.bunifuGradientPanel1.TabIndex = 1;
            // 
            // bunifuCustomLabel1
            // 
            this.bunifuCustomLabel1.AutoSize = true;
            this.bunifuCustomLabel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuCustomLabel1.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuCustomLabel1.Location = new System.Drawing.Point(376, 12);
            this.bunifuCustomLabel1.Name = "bunifuCustomLabel1";
            this.bunifuCustomLabel1.Size = new System.Drawing.Size(228, 32);
            this.bunifuCustomLabel1.TabIndex = 2;
            this.bunifuCustomLabel1.Text = "Razones Financieras";
            // 
            // btn_salir
            // 
            this.btn_salir.BackColor = System.Drawing.Color.DodgerBlue;
            this.btn_salir.Image = ((System.Drawing.Image)(resources.GetObject("btn_salir.Image")));
            this.btn_salir.ImageActive = null;
            this.btn_salir.Location = new System.Drawing.Point(943, 0);
            this.btn_salir.Name = "btn_salir";
            this.btn_salir.Size = new System.Drawing.Size(37, 37);
            this.btn_salir.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btn_salir.TabIndex = 1;
            this.btn_salir.TabStop = false;
            this.btn_salir.Zoom = 10;
            this.btn_salir.Click += new System.EventHandler(this.btn_salir_Click);
            // 
            // bunifuDatePicker1
            // 
            this.bunifuDatePicker1.BackColor = System.Drawing.Color.DodgerBlue;
            this.bunifuDatePicker1.BorderRadius = 1;
            this.bunifuDatePicker1.Color = System.Drawing.Color.White;
            this.bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.DisplayWeekNumbers = false;
            this.bunifuDatePicker1.DPHeight = 0;
            this.bunifuDatePicker1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.bunifuDatePicker1.FillDatePicker = false;
            this.bunifuDatePicker1.ForeColor = System.Drawing.Color.White;
            this.bunifuDatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker1.Icon")));
            this.bunifuDatePicker1.IconColor = System.Drawing.Color.White;
            this.bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker1.Location = new System.Drawing.Point(67, 12);
            this.bunifuDatePicker1.MaxDate = new System.DateTime(2020, 12, 31, 0, 0, 0, 0);
            this.bunifuDatePicker1.MinDate = new System.DateTime(1990, 1, 1, 0, 0, 0, 0);
            this.bunifuDatePicker1.MinimumSize = new System.Drawing.Size(217, 32);
            this.bunifuDatePicker1.Name = "bunifuDatePicker1";
            this.bunifuDatePicker1.Size = new System.Drawing.Size(217, 32);
            this.bunifuDatePicker1.TabIndex = 0;
            this.bunifuDatePicker1.Value = new System.DateTime(2020, 1, 1, 0, 0, 0, 0);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.btn_RotInt);
            this.groupBox2.Controls.Add(this.btn_deuda);
            this.groupBox2.Controls.Add(this.btn_PasivoCap);
            this.groupBox2.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox2.ForeColor = System.Drawing.Color.DodgerBlue;
            this.groupBox2.Location = new System.Drawing.Point(12, 324);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(438, 222);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Razones de endeudamiento";
            // 
            // btn_RotInt
            // 
            this.btn_RotInt.AllowToggling = false;
            this.btn_RotInt.AnimationSpeed = 200;
            this.btn_RotInt.AutoGenerateColors = false;
            this.btn_RotInt.BackColor = System.Drawing.Color.Transparent;
            this.btn_RotInt.BackColor1 = System.Drawing.Color.White;
            this.btn_RotInt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_RotInt.BackgroundImage")));
            this.btn_RotInt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_RotInt.ButtonText = "Razón de rotación de interes";
            this.btn_RotInt.ButtonTextMarginLeft = -10;
            this.btn_RotInt.ColorContrastOnClick = 45;
            this.btn_RotInt.ColorContrastOnHover = 45;
            this.btn_RotInt.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_RotInt.CustomizableEdges = borderEdges4;
            this.btn_RotInt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_RotInt.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_RotInt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_RotInt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_RotInt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_RotInt.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_RotInt.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_RotInt.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_RotInt.IconMarginLeft = 11;
            this.btn_RotInt.IconPadding = 10;
            this.btn_RotInt.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_RotInt.IdleBorderColor = System.Drawing.Color.White;
            this.btn_RotInt.IdleBorderRadius = 3;
            this.btn_RotInt.IdleBorderThickness = 1;
            this.btn_RotInt.IdleFillColor = System.Drawing.Color.White;
            this.btn_RotInt.IdleIconLeftImage = null;
            this.btn_RotInt.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_RotInt.IdleIconRightImage")));
            this.btn_RotInt.IndicateFocus = false;
            this.btn_RotInt.Location = new System.Drawing.Point(6, 150);
            this.btn_RotInt.Name = "btn_RotInt";
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.BorderRadius = 3;
            stateProperties7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties7.BorderThickness = 1;
            stateProperties7.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.ForeColor = System.Drawing.Color.White;
            stateProperties7.IconLeftImage = null;
            stateProperties7.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties7.IconRightImage")));
            this.btn_RotInt.onHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.White;
            stateProperties8.BorderRadius = 3;
            stateProperties8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties8.BorderThickness = 1;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties8.IconLeftImage = null;
            stateProperties8.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties8.IconRightImage")));
            this.btn_RotInt.OnPressedState = stateProperties8;
            this.btn_RotInt.Size = new System.Drawing.Size(232, 45);
            this.btn_RotInt.TabIndex = 5;
            this.btn_RotInt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_RotInt.TextMarginLeft = -10;
            this.btn_RotInt.UseDefaultRadiusAndThickness = true;
            // 
            // btn_deuda
            // 
            this.btn_deuda.AllowToggling = false;
            this.btn_deuda.AnimationSpeed = 200;
            this.btn_deuda.AutoGenerateColors = false;
            this.btn_deuda.BackColor = System.Drawing.Color.Transparent;
            this.btn_deuda.BackColor1 = System.Drawing.Color.White;
            this.btn_deuda.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_deuda.BackgroundImage")));
            this.btn_deuda.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_deuda.ButtonText = "Razón de deuda";
            this.btn_deuda.ButtonTextMarginLeft = -47;
            this.btn_deuda.ColorContrastOnClick = 45;
            this.btn_deuda.ColorContrastOnHover = 45;
            this.btn_deuda.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btn_deuda.CustomizableEdges = borderEdges5;
            this.btn_deuda.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_deuda.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_deuda.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_deuda.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_deuda.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_deuda.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_deuda.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_deuda.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_deuda.IconMarginLeft = 11;
            this.btn_deuda.IconPadding = 10;
            this.btn_deuda.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_deuda.IdleBorderColor = System.Drawing.Color.White;
            this.btn_deuda.IdleBorderRadius = 3;
            this.btn_deuda.IdleBorderThickness = 1;
            this.btn_deuda.IdleFillColor = System.Drawing.Color.White;
            this.btn_deuda.IdleIconLeftImage = null;
            this.btn_deuda.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_deuda.IdleIconRightImage")));
            this.btn_deuda.IndicateFocus = false;
            this.btn_deuda.Location = new System.Drawing.Point(6, 48);
            this.btn_deuda.Name = "btn_deuda";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties9.BorderRadius = 3;
            stateProperties9.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties9.BorderThickness = 1;
            stateProperties9.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties9.ForeColor = System.Drawing.Color.White;
            stateProperties9.IconLeftImage = null;
            stateProperties9.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties9.IconRightImage")));
            this.btn_deuda.onHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.White;
            stateProperties10.BorderRadius = 3;
            stateProperties10.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties10.BorderThickness = 1;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties10.IconLeftImage = null;
            stateProperties10.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties10.IconRightImage")));
            this.btn_deuda.OnPressedState = stateProperties10;
            this.btn_deuda.Size = new System.Drawing.Size(232, 45);
            this.btn_deuda.TabIndex = 4;
            this.btn_deuda.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_deuda.TextMarginLeft = -47;
            this.btn_deuda.UseDefaultRadiusAndThickness = true;
            this.btn_deuda.Click += new System.EventHandler(this.btn_deuda_Click);
            // 
            // btn_PasivoCap
            // 
            this.btn_PasivoCap.AllowToggling = false;
            this.btn_PasivoCap.AnimationSpeed = 200;
            this.btn_PasivoCap.AutoGenerateColors = false;
            this.btn_PasivoCap.BackColor = System.Drawing.Color.Transparent;
            this.btn_PasivoCap.BackColor1 = System.Drawing.Color.White;
            this.btn_PasivoCap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_PasivoCap.BackgroundImage")));
            this.btn_PasivoCap.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PasivoCap.ButtonText = "Razón pasivo a capital";
            this.btn_PasivoCap.ButtonTextMarginLeft = -30;
            this.btn_PasivoCap.ColorContrastOnClick = 45;
            this.btn_PasivoCap.ColorContrastOnHover = 45;
            this.btn_PasivoCap.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btn_PasivoCap.CustomizableEdges = borderEdges6;
            this.btn_PasivoCap.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_PasivoCap.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_PasivoCap.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_PasivoCap.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_PasivoCap.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_PasivoCap.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_PasivoCap.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_PasivoCap.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_PasivoCap.IconMarginLeft = 11;
            this.btn_PasivoCap.IconPadding = 10;
            this.btn_PasivoCap.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_PasivoCap.IdleBorderColor = System.Drawing.Color.White;
            this.btn_PasivoCap.IdleBorderRadius = 3;
            this.btn_PasivoCap.IdleBorderThickness = 1;
            this.btn_PasivoCap.IdleFillColor = System.Drawing.Color.White;
            this.btn_PasivoCap.IdleIconLeftImage = null;
            this.btn_PasivoCap.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_PasivoCap.IdleIconRightImage")));
            this.btn_PasivoCap.IndicateFocus = false;
            this.btn_PasivoCap.Location = new System.Drawing.Point(6, 99);
            this.btn_PasivoCap.Name = "btn_PasivoCap";
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.BorderRadius = 3;
            stateProperties11.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties11.BorderThickness = 1;
            stateProperties11.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.ForeColor = System.Drawing.Color.White;
            stateProperties11.IconLeftImage = null;
            stateProperties11.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties11.IconRightImage")));
            this.btn_PasivoCap.onHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.White;
            stateProperties12.BorderRadius = 3;
            stateProperties12.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties12.BorderThickness = 1;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties12.IconLeftImage = null;
            stateProperties12.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties12.IconRightImage")));
            this.btn_PasivoCap.OnPressedState = stateProperties12;
            this.btn_PasivoCap.Size = new System.Drawing.Size(232, 45);
            this.btn_PasivoCap.TabIndex = 3;
            this.btn_PasivoCap.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_PasivoCap.TextMarginLeft = -30;
            this.btn_PasivoCap.UseDefaultRadiusAndThickness = true;
            this.btn_PasivoCap.Click += new System.EventHandler(this.btn_PasivoCap_Click);
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.btn_ActivoTotal);
            this.groupBox3.Controls.Add(this.btn_ActivoFijo);
            this.groupBox3.Controls.Add(this.btn_PeriCobro);
            this.groupBox3.Controls.Add(this.btn_rotaciónInventario);
            this.groupBox3.Controls.Add(this.btn_CuentasCobrar);
            this.groupBox3.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox3.ForeColor = System.Drawing.Color.DodgerBlue;
            this.groupBox3.Location = new System.Drawing.Point(498, 79);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(463, 222);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Razones de actividad";
            // 
            // btn_ActivoTotal
            // 
            this.btn_ActivoTotal.AllowToggling = false;
            this.btn_ActivoTotal.AnimationSpeed = 200;
            this.btn_ActivoTotal.AutoGenerateColors = false;
            this.btn_ActivoTotal.BackColor = System.Drawing.Color.Transparent;
            this.btn_ActivoTotal.BackColor1 = System.Drawing.Color.White;
            this.btn_ActivoTotal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ActivoTotal.BackgroundImage")));
            this.btn_ActivoTotal.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ActivoTotal.ButtonText = "Rotación de activos totales";
            this.btn_ActivoTotal.ButtonTextMarginLeft = -20;
            this.btn_ActivoTotal.ColorContrastOnClick = 45;
            this.btn_ActivoTotal.ColorContrastOnHover = 45;
            this.btn_ActivoTotal.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btn_ActivoTotal.CustomizableEdges = borderEdges7;
            this.btn_ActivoTotal.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ActivoTotal.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_ActivoTotal.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ActivoTotal.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ActivoTotal.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ActivoTotal.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_ActivoTotal.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_ActivoTotal.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_ActivoTotal.IconMarginLeft = 11;
            this.btn_ActivoTotal.IconPadding = 10;
            this.btn_ActivoTotal.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_ActivoTotal.IdleBorderColor = System.Drawing.Color.White;
            this.btn_ActivoTotal.IdleBorderRadius = 3;
            this.btn_ActivoTotal.IdleBorderThickness = 1;
            this.btn_ActivoTotal.IdleFillColor = System.Drawing.Color.White;
            this.btn_ActivoTotal.IdleIconLeftImage = null;
            this.btn_ActivoTotal.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_ActivoTotal.IdleIconRightImage")));
            this.btn_ActivoTotal.IndicateFocus = false;
            this.btn_ActivoTotal.Location = new System.Drawing.Point(244, 94);
            this.btn_ActivoTotal.Name = "btn_ActivoTotal";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.BorderRadius = 3;
            stateProperties13.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties13.BorderThickness = 1;
            stateProperties13.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.ForeColor = System.Drawing.Color.White;
            stateProperties13.IconLeftImage = null;
            stateProperties13.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties13.IconRightImage")));
            this.btn_ActivoTotal.onHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.White;
            stateProperties14.BorderRadius = 3;
            stateProperties14.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties14.BorderThickness = 1;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties14.IconLeftImage = null;
            stateProperties14.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties14.IconRightImage")));
            this.btn_ActivoTotal.OnPressedState = stateProperties14;
            this.btn_ActivoTotal.Size = new System.Drawing.Size(219, 45);
            this.btn_ActivoTotal.TabIndex = 10;
            this.btn_ActivoTotal.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ActivoTotal.TextMarginLeft = -20;
            this.btn_ActivoTotal.UseDefaultRadiusAndThickness = true;
            this.btn_ActivoTotal.Click += new System.EventHandler(this.btn_ActivoTotal_Click);
            // 
            // btn_ActivoFijo
            // 
            this.btn_ActivoFijo.AllowToggling = false;
            this.btn_ActivoFijo.AnimationSpeed = 200;
            this.btn_ActivoFijo.AutoGenerateColors = false;
            this.btn_ActivoFijo.BackColor = System.Drawing.Color.Transparent;
            this.btn_ActivoFijo.BackColor1 = System.Drawing.Color.White;
            this.btn_ActivoFijo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_ActivoFijo.BackgroundImage")));
            this.btn_ActivoFijo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_ActivoFijo.ButtonText = "Rotación de activo fijo";
            this.btn_ActivoFijo.ButtonTextMarginLeft = -33;
            this.btn_ActivoFijo.ColorContrastOnClick = 45;
            this.btn_ActivoFijo.ColorContrastOnHover = 45;
            this.btn_ActivoFijo.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btn_ActivoFijo.CustomizableEdges = borderEdges8;
            this.btn_ActivoFijo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_ActivoFijo.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_ActivoFijo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_ActivoFijo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_ActivoFijo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_ActivoFijo.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_ActivoFijo.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_ActivoFijo.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_ActivoFijo.IconMarginLeft = 11;
            this.btn_ActivoFijo.IconPadding = 10;
            this.btn_ActivoFijo.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_ActivoFijo.IdleBorderColor = System.Drawing.Color.White;
            this.btn_ActivoFijo.IdleBorderRadius = 3;
            this.btn_ActivoFijo.IdleBorderThickness = 1;
            this.btn_ActivoFijo.IdleFillColor = System.Drawing.Color.White;
            this.btn_ActivoFijo.IdleIconLeftImage = null;
            this.btn_ActivoFijo.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_ActivoFijo.IdleIconRightImage")));
            this.btn_ActivoFijo.IndicateFocus = false;
            this.btn_ActivoFijo.Location = new System.Drawing.Point(244, 43);
            this.btn_ActivoFijo.Name = "btn_ActivoFijo";
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.BorderRadius = 3;
            stateProperties15.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties15.BorderThickness = 1;
            stateProperties15.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.ForeColor = System.Drawing.Color.White;
            stateProperties15.IconLeftImage = null;
            stateProperties15.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties15.IconRightImage")));
            this.btn_ActivoFijo.onHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.White;
            stateProperties16.BorderRadius = 3;
            stateProperties16.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties16.BorderThickness = 1;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties16.IconLeftImage = null;
            stateProperties16.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties16.IconRightImage")));
            this.btn_ActivoFijo.OnPressedState = stateProperties16;
            this.btn_ActivoFijo.Size = new System.Drawing.Size(219, 45);
            this.btn_ActivoFijo.TabIndex = 9;
            this.btn_ActivoFijo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_ActivoFijo.TextMarginLeft = -33;
            this.btn_ActivoFijo.UseDefaultRadiusAndThickness = true;
            this.btn_ActivoFijo.Click += new System.EventHandler(this.btn_ActivoFijo_Click);
            // 
            // btn_PeriCobro
            // 
            this.btn_PeriCobro.AllowToggling = false;
            this.btn_PeriCobro.AnimationSpeed = 200;
            this.btn_PeriCobro.AutoGenerateColors = false;
            this.btn_PeriCobro.BackColor = System.Drawing.Color.Transparent;
            this.btn_PeriCobro.BackColor1 = System.Drawing.Color.White;
            this.btn_PeriCobro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_PeriCobro.BackgroundImage")));
            this.btn_PeriCobro.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_PeriCobro.ButtonText = "Período promedio de cobro";
            this.btn_PeriCobro.ButtonTextMarginLeft = -25;
            this.btn_PeriCobro.ColorContrastOnClick = 45;
            this.btn_PeriCobro.ColorContrastOnHover = 45;
            this.btn_PeriCobro.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btn_PeriCobro.CustomizableEdges = borderEdges9;
            this.btn_PeriCobro.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_PeriCobro.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_PeriCobro.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_PeriCobro.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_PeriCobro.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_PeriCobro.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_PeriCobro.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_PeriCobro.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_PeriCobro.IconMarginLeft = 11;
            this.btn_PeriCobro.IconPadding = 10;
            this.btn_PeriCobro.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_PeriCobro.IdleBorderColor = System.Drawing.Color.White;
            this.btn_PeriCobro.IdleBorderRadius = 3;
            this.btn_PeriCobro.IdleBorderThickness = 1;
            this.btn_PeriCobro.IdleFillColor = System.Drawing.Color.White;
            this.btn_PeriCobro.IdleIconLeftImage = null;
            this.btn_PeriCobro.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_PeriCobro.IdleIconRightImage")));
            this.btn_PeriCobro.IndicateFocus = false;
            this.btn_PeriCobro.Location = new System.Drawing.Point(23, 94);
            this.btn_PeriCobro.Name = "btn_PeriCobro";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties17.BorderRadius = 3;
            stateProperties17.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties17.BorderThickness = 1;
            stateProperties17.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties17.ForeColor = System.Drawing.Color.White;
            stateProperties17.IconLeftImage = null;
            stateProperties17.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties17.IconRightImage")));
            this.btn_PeriCobro.onHoverState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.White;
            stateProperties18.BorderRadius = 3;
            stateProperties18.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties18.BorderThickness = 1;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties18.IconLeftImage = null;
            stateProperties18.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties18.IconRightImage")));
            this.btn_PeriCobro.OnPressedState = stateProperties18;
            this.btn_PeriCobro.Size = new System.Drawing.Size(223, 45);
            this.btn_PeriCobro.TabIndex = 8;
            this.btn_PeriCobro.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_PeriCobro.TextMarginLeft = -25;
            this.btn_PeriCobro.UseDefaultRadiusAndThickness = true;
            this.btn_PeriCobro.Click += new System.EventHandler(this.btn_PeriCobro_Click);
            // 
            // btn_rotaciónInventario
            // 
            this.btn_rotaciónInventario.AllowToggling = false;
            this.btn_rotaciónInventario.AnimationSpeed = 200;
            this.btn_rotaciónInventario.AutoGenerateColors = false;
            this.btn_rotaciónInventario.BackColor = System.Drawing.Color.Transparent;
            this.btn_rotaciónInventario.BackColor1 = System.Drawing.Color.White;
            this.btn_rotaciónInventario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_rotaciónInventario.BackgroundImage")));
            this.btn_rotaciónInventario.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_rotaciónInventario.ButtonText = "Rotación de inventario";
            this.btn_rotaciónInventario.ButtonTextMarginLeft = -43;
            this.btn_rotaciónInventario.ColorContrastOnClick = 45;
            this.btn_rotaciónInventario.ColorContrastOnHover = 45;
            this.btn_rotaciónInventario.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btn_rotaciónInventario.CustomizableEdges = borderEdges10;
            this.btn_rotaciónInventario.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_rotaciónInventario.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_rotaciónInventario.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_rotaciónInventario.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_rotaciónInventario.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_rotaciónInventario.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_rotaciónInventario.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_rotaciónInventario.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_rotaciónInventario.IconMarginLeft = 11;
            this.btn_rotaciónInventario.IconPadding = 10;
            this.btn_rotaciónInventario.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_rotaciónInventario.IdleBorderColor = System.Drawing.Color.White;
            this.btn_rotaciónInventario.IdleBorderRadius = 3;
            this.btn_rotaciónInventario.IdleBorderThickness = 1;
            this.btn_rotaciónInventario.IdleFillColor = System.Drawing.Color.White;
            this.btn_rotaciónInventario.IdleIconLeftImage = null;
            this.btn_rotaciónInventario.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_rotaciónInventario.IdleIconRightImage")));
            this.btn_rotaciónInventario.IndicateFocus = false;
            this.btn_rotaciónInventario.Location = new System.Drawing.Point(23, 43);
            this.btn_rotaciónInventario.Name = "btn_rotaciónInventario";
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.BorderRadius = 3;
            stateProperties19.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties19.BorderThickness = 1;
            stateProperties19.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.ForeColor = System.Drawing.Color.White;
            stateProperties19.IconLeftImage = null;
            stateProperties19.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties19.IconRightImage")));
            this.btn_rotaciónInventario.onHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.White;
            stateProperties20.BorderRadius = 3;
            stateProperties20.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties20.BorderThickness = 1;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties20.IconLeftImage = null;
            stateProperties20.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties20.IconRightImage")));
            this.btn_rotaciónInventario.OnPressedState = stateProperties20;
            this.btn_rotaciónInventario.Size = new System.Drawing.Size(223, 45);
            this.btn_rotaciónInventario.TabIndex = 7;
            this.btn_rotaciónInventario.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_rotaciónInventario.TextMarginLeft = -43;
            this.btn_rotaciónInventario.UseDefaultRadiusAndThickness = true;
            // 
            // btn_CuentasCobrar
            // 
            this.btn_CuentasCobrar.AllowToggling = false;
            this.btn_CuentasCobrar.AnimationSpeed = 200;
            this.btn_CuentasCobrar.AutoGenerateColors = false;
            this.btn_CuentasCobrar.BackColor = System.Drawing.Color.Transparent;
            this.btn_CuentasCobrar.BackColor1 = System.Drawing.Color.White;
            this.btn_CuentasCobrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_CuentasCobrar.BackgroundImage")));
            this.btn_CuentasCobrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_CuentasCobrar.ButtonText = "Rotación cuentas por cobrar";
            this.btn_CuentasCobrar.ButtonTextMarginLeft = -25;
            this.btn_CuentasCobrar.ColorContrastOnClick = 45;
            this.btn_CuentasCobrar.ColorContrastOnHover = 45;
            this.btn_CuentasCobrar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btn_CuentasCobrar.CustomizableEdges = borderEdges11;
            this.btn_CuentasCobrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_CuentasCobrar.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_CuentasCobrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_CuentasCobrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_CuentasCobrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_CuentasCobrar.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_CuentasCobrar.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_CuentasCobrar.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_CuentasCobrar.IconMarginLeft = 11;
            this.btn_CuentasCobrar.IconPadding = 10;
            this.btn_CuentasCobrar.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_CuentasCobrar.IdleBorderColor = System.Drawing.Color.White;
            this.btn_CuentasCobrar.IdleBorderRadius = 3;
            this.btn_CuentasCobrar.IdleBorderThickness = 1;
            this.btn_CuentasCobrar.IdleFillColor = System.Drawing.Color.White;
            this.btn_CuentasCobrar.IdleIconLeftImage = null;
            this.btn_CuentasCobrar.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_CuentasCobrar.IdleIconRightImage")));
            this.btn_CuentasCobrar.IndicateFocus = false;
            this.btn_CuentasCobrar.Location = new System.Drawing.Point(23, 145);
            this.btn_CuentasCobrar.Name = "btn_CuentasCobrar";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.BorderRadius = 3;
            stateProperties21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties21.BorderThickness = 1;
            stateProperties21.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.IconLeftImage = null;
            stateProperties21.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties21.IconRightImage")));
            this.btn_CuentasCobrar.onHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.White;
            stateProperties22.BorderRadius = 3;
            stateProperties22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties22.BorderThickness = 1;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties22.IconLeftImage = null;
            stateProperties22.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties22.IconRightImage")));
            this.btn_CuentasCobrar.OnPressedState = stateProperties22;
            this.btn_CuentasCobrar.Size = new System.Drawing.Size(223, 45);
            this.btn_CuentasCobrar.TabIndex = 6;
            this.btn_CuentasCobrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_CuentasCobrar.TextMarginLeft = -25;
            this.btn_CuentasCobrar.UseDefaultRadiusAndThickness = true;
            this.btn_CuentasCobrar.Click += new System.EventHandler(this.btn_CuentasCobrar_Click);
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.btn_UtilidadNeta);
            this.groupBox4.Controls.Add(this.btn_UtilidadBruta);
            this.groupBox4.Controls.Add(this.btn_UtilidadOper);
            this.groupBox4.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.groupBox4.ForeColor = System.Drawing.Color.DodgerBlue;
            this.groupBox4.Location = new System.Drawing.Point(498, 324);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(463, 222);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Razones de rentabilidad";
            // 
            // btn_UtilidadNeta
            // 
            this.btn_UtilidadNeta.AllowToggling = false;
            this.btn_UtilidadNeta.AnimationSpeed = 200;
            this.btn_UtilidadNeta.AutoGenerateColors = false;
            this.btn_UtilidadNeta.BackColor = System.Drawing.Color.Transparent;
            this.btn_UtilidadNeta.BackColor1 = System.Drawing.Color.White;
            this.btn_UtilidadNeta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UtilidadNeta.BackgroundImage")));
            this.btn_UtilidadNeta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UtilidadNeta.ButtonText = "Margen de utilidad neta";
            this.btn_UtilidadNeta.ButtonTextMarginLeft = -25;
            this.btn_UtilidadNeta.ColorContrastOnClick = 45;
            this.btn_UtilidadNeta.ColorContrastOnHover = 45;
            this.btn_UtilidadNeta.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btn_UtilidadNeta.CustomizableEdges = borderEdges12;
            this.btn_UtilidadNeta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UtilidadNeta.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_UtilidadNeta.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UtilidadNeta.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UtilidadNeta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UtilidadNeta.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_UtilidadNeta.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_UtilidadNeta.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_UtilidadNeta.IconMarginLeft = 11;
            this.btn_UtilidadNeta.IconPadding = 10;
            this.btn_UtilidadNeta.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_UtilidadNeta.IdleBorderColor = System.Drawing.Color.White;
            this.btn_UtilidadNeta.IdleBorderRadius = 3;
            this.btn_UtilidadNeta.IdleBorderThickness = 1;
            this.btn_UtilidadNeta.IdleFillColor = System.Drawing.Color.White;
            this.btn_UtilidadNeta.IdleIconLeftImage = null;
            this.btn_UtilidadNeta.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_UtilidadNeta.IdleIconRightImage")));
            this.btn_UtilidadNeta.IndicateFocus = false;
            this.btn_UtilidadNeta.Location = new System.Drawing.Point(23, 150);
            this.btn_UtilidadNeta.Name = "btn_UtilidadNeta";
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.BorderRadius = 3;
            stateProperties23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties23.BorderThickness = 1;
            stateProperties23.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.ForeColor = System.Drawing.Color.White;
            stateProperties23.IconLeftImage = null;
            stateProperties23.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties23.IconRightImage")));
            this.btn_UtilidadNeta.onHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.White;
            stateProperties24.BorderRadius = 3;
            stateProperties24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties24.BorderThickness = 1;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties24.IconLeftImage = null;
            stateProperties24.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties24.IconRightImage")));
            this.btn_UtilidadNeta.OnPressedState = stateProperties24;
            this.btn_UtilidadNeta.Size = new System.Drawing.Size(223, 45);
            this.btn_UtilidadNeta.TabIndex = 5;
            this.btn_UtilidadNeta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UtilidadNeta.TextMarginLeft = -25;
            this.btn_UtilidadNeta.UseDefaultRadiusAndThickness = true;
            this.btn_UtilidadNeta.Click += new System.EventHandler(this.btn_UtilidadNeta_Click);
            // 
            // btn_UtilidadBruta
            // 
            this.btn_UtilidadBruta.AllowToggling = false;
            this.btn_UtilidadBruta.AnimationSpeed = 200;
            this.btn_UtilidadBruta.AutoGenerateColors = false;
            this.btn_UtilidadBruta.BackColor = System.Drawing.Color.Transparent;
            this.btn_UtilidadBruta.BackColor1 = System.Drawing.Color.White;
            this.btn_UtilidadBruta.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UtilidadBruta.BackgroundImage")));
            this.btn_UtilidadBruta.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UtilidadBruta.ButtonText = "Margen de utilidad bruta";
            this.btn_UtilidadBruta.ButtonTextMarginLeft = -23;
            this.btn_UtilidadBruta.ColorContrastOnClick = 45;
            this.btn_UtilidadBruta.ColorContrastOnHover = 45;
            this.btn_UtilidadBruta.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btn_UtilidadBruta.CustomizableEdges = borderEdges13;
            this.btn_UtilidadBruta.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UtilidadBruta.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_UtilidadBruta.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UtilidadBruta.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UtilidadBruta.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UtilidadBruta.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_UtilidadBruta.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_UtilidadBruta.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_UtilidadBruta.IconMarginLeft = 11;
            this.btn_UtilidadBruta.IconPadding = 10;
            this.btn_UtilidadBruta.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_UtilidadBruta.IdleBorderColor = System.Drawing.Color.White;
            this.btn_UtilidadBruta.IdleBorderRadius = 3;
            this.btn_UtilidadBruta.IdleBorderThickness = 1;
            this.btn_UtilidadBruta.IdleFillColor = System.Drawing.Color.White;
            this.btn_UtilidadBruta.IdleIconLeftImage = null;
            this.btn_UtilidadBruta.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_UtilidadBruta.IdleIconRightImage")));
            this.btn_UtilidadBruta.IndicateFocus = false;
            this.btn_UtilidadBruta.Location = new System.Drawing.Point(23, 48);
            this.btn_UtilidadBruta.Name = "btn_UtilidadBruta";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.BorderRadius = 3;
            stateProperties25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties25.BorderThickness = 1;
            stateProperties25.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.IconLeftImage = null;
            stateProperties25.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties25.IconRightImage")));
            this.btn_UtilidadBruta.onHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.White;
            stateProperties26.BorderRadius = 3;
            stateProperties26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties26.BorderThickness = 1;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties26.IconLeftImage = null;
            stateProperties26.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties26.IconRightImage")));
            this.btn_UtilidadBruta.OnPressedState = stateProperties26;
            this.btn_UtilidadBruta.Size = new System.Drawing.Size(223, 45);
            this.btn_UtilidadBruta.TabIndex = 4;
            this.btn_UtilidadBruta.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UtilidadBruta.TextMarginLeft = -23;
            this.btn_UtilidadBruta.UseDefaultRadiusAndThickness = true;
            this.btn_UtilidadBruta.Click += new System.EventHandler(this.btn_UtilidadBruta_Click);
            // 
            // btn_UtilidadOper
            // 
            this.btn_UtilidadOper.AllowToggling = false;
            this.btn_UtilidadOper.AnimationSpeed = 200;
            this.btn_UtilidadOper.AutoGenerateColors = false;
            this.btn_UtilidadOper.BackColor = System.Drawing.Color.Transparent;
            this.btn_UtilidadOper.BackColor1 = System.Drawing.Color.White;
            this.btn_UtilidadOper.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_UtilidadOper.BackgroundImage")));
            this.btn_UtilidadOper.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_UtilidadOper.ButtonText = "Margen de utilidad operativa";
            this.btn_UtilidadOper.ButtonTextMarginLeft = -10;
            this.btn_UtilidadOper.ColorContrastOnClick = 45;
            this.btn_UtilidadOper.ColorContrastOnHover = 45;
            this.btn_UtilidadOper.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btn_UtilidadOper.CustomizableEdges = borderEdges14;
            this.btn_UtilidadOper.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_UtilidadOper.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_UtilidadOper.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_UtilidadOper.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_UtilidadOper.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_UtilidadOper.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_UtilidadOper.ForeColor = System.Drawing.Color.DodgerBlue;
            this.btn_UtilidadOper.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_UtilidadOper.IconMarginLeft = 11;
            this.btn_UtilidadOper.IconPadding = 10;
            this.btn_UtilidadOper.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_UtilidadOper.IdleBorderColor = System.Drawing.Color.White;
            this.btn_UtilidadOper.IdleBorderRadius = 3;
            this.btn_UtilidadOper.IdleBorderThickness = 1;
            this.btn_UtilidadOper.IdleFillColor = System.Drawing.Color.White;
            this.btn_UtilidadOper.IdleIconLeftImage = null;
            this.btn_UtilidadOper.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btn_UtilidadOper.IdleIconRightImage")));
            this.btn_UtilidadOper.IndicateFocus = false;
            this.btn_UtilidadOper.Location = new System.Drawing.Point(23, 99);
            this.btn_UtilidadOper.Name = "btn_UtilidadOper";
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.BorderRadius = 3;
            stateProperties27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties27.BorderThickness = 1;
            stateProperties27.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.ForeColor = System.Drawing.Color.White;
            stateProperties27.IconLeftImage = null;
            stateProperties27.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties27.IconRightImage")));
            this.btn_UtilidadOper.onHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.White;
            stateProperties28.BorderRadius = 3;
            stateProperties28.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties28.BorderThickness = 1;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.DodgerBlue;
            stateProperties28.IconLeftImage = null;
            stateProperties28.IconRightImage = ((System.Drawing.Image)(resources.GetObject("stateProperties28.IconRightImage")));
            this.btn_UtilidadOper.OnPressedState = stateProperties28;
            this.btn_UtilidadOper.Size = new System.Drawing.Size(223, 45);
            this.btn_UtilidadOper.TabIndex = 3;
            this.btn_UtilidadOper.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_UtilidadOper.TextMarginLeft = -10;
            this.btn_UtilidadOper.UseDefaultRadiusAndThickness = true;
            this.btn_UtilidadOper.Click += new System.EventHandler(this.btn_UtilidadOper_Click);
            // 
            // bunifuFlatButton1
            // 
            this.bunifuFlatButton1.Active = false;
            this.bunifuFlatButton1.Activecolor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(243)))), ((int)(((byte)(243)))));
            this.bunifuFlatButton1.BackColor = System.Drawing.Color.White;
            this.bunifuFlatButton1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuFlatButton1.BorderRadius = 0;
            this.bunifuFlatButton1.ButtonText = "Análisis entre años";
            this.bunifuFlatButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuFlatButton1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuFlatButton1.Iconcolor = System.Drawing.Color.Transparent;
            this.bunifuFlatButton1.Iconimage = null;
            this.bunifuFlatButton1.Iconimage_right = null;
            this.bunifuFlatButton1.Iconimage_right_Selected = null;
            this.bunifuFlatButton1.Iconimage_Selected = null;
            this.bunifuFlatButton1.IconMarginLeft = 0;
            this.bunifuFlatButton1.IconMarginRight = 0;
            this.bunifuFlatButton1.IconRightVisible = true;
            this.bunifuFlatButton1.IconRightZoom = 0D;
            this.bunifuFlatButton1.IconVisible = true;
            this.bunifuFlatButton1.IconZoom = 90D;
            this.bunifuFlatButton1.IsTab = false;
            this.bunifuFlatButton1.Location = new System.Drawing.Point(717, 561);
            this.bunifuFlatButton1.Name = "bunifuFlatButton1";
            this.bunifuFlatButton1.Normalcolor = System.Drawing.Color.White;
            this.bunifuFlatButton1.OnHovercolor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(243)))), ((int)(((byte)(243)))));
            this.bunifuFlatButton1.OnHoverTextColor = System.Drawing.Color.DodgerBlue;
            this.bunifuFlatButton1.selected = false;
            this.bunifuFlatButton1.Size = new System.Drawing.Size(217, 37);
            this.bunifuFlatButton1.TabIndex = 4;
            this.bunifuFlatButton1.Text = "Análisis entre años";
            this.bunifuFlatButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuFlatButton1.Textcolor = System.Drawing.Color.DodgerBlue;
            this.bunifuFlatButton1.TextFont = new System.Drawing.Font("Segoe UI", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 7;
            this.bunifuElipse1.TargetControl = this;
            // 
            // RazonesFinancieras
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(980, 610);
            this.Controls.Add(this.bunifuFlatButton1);
            this.Controls.Add(this.groupBox4);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.groupBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "RazonesFinancieras";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "RazonesFinancieras";
            this.Load += new System.EventHandler(this.RazonesFinancieras_Load);
            this.groupBox1.ResumeLayout(false);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btn_salir)).EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox groupBox1;
        private Bunifu.Framework.UI.BunifuGradientPanel bunifuGradientPanel1;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.GroupBox groupBox4;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
        private Bunifu.Framework.UI.BunifuImageButton btn_salir;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel1;
        private Bunifu.Framework.UI.BunifuFlatButton bunifuFlatButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_is;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_pa;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_cnt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_RotInt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_deuda;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_PasivoCap;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UtilidadNeta;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UtilidadBruta;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_UtilidadOper;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_PeriCobro;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_rotaciónInventario;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_CuentasCobrar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ActivoTotal;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_ActivoFijo;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
    }
}